import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import DiscountInput from '../components/DiscountInput'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [discounts, setDiscounts] = useState([0])

  // const changeValueDiscount = () => {

  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {discounts.map((discount, i) => {
          return <DiscountInput key={i} value={discount} changeValue={(e) => {
            const temp = discounts
            temp[i] = e.target.value
            console.log(temp);
            setDiscounts(temp)
          }}/>
        })}
      </main>
    </div>
  )
}
